FenXs/FenXs/Pages/Settings/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using PageModels.UserPageModel;
using FenXsData.Models.ChangeEmailModel;
using FenXsData.Models.ChangePasswordModel;
using FenXsData.Models.RemoveAccountModel;
using FenXs.DataAccessLayer.Account;
using ILogger = FenXsData.Infrastructure.Logger.ILogger;

namespace FenXs.Pages;

public class SettingsIndexModel : UserPageModel
{
    private Account account;
    [BindProperty]
    public ChangeEmail? ce { get; set; }
    [BindProperty]
    public ChangePassword? cp { get; set; }
    [BindProperty]
    public RemoveAccount? ra { get; set; }
    public bool dangerBox, warningBox, successBox;
    public string? info;

    public SettingsIndexModel(IConfiguration configuration, ILogger _logger)
    {
        account = new Account(configuration, _logger);
    }

    public void OnPostChangeEmail()
    {
        successBox = warningBox = dangerBox = false;
        if (ModelState.ErrorCount - 4 == 0)
        {
            if (!(String.Compare(ce!.oldEmail, HttpContext.Session.GetString("email")) == 0))
            {
                dangerBox = true;
                info = "Wrong old email provided.";
            }
            else if (String.Compare(ce.oldEmail, ce.newEmail) == 0)
            {
                warningBox = true;
                info = "The new email address cannot be the same as the old email address.";
            }
            else
            {
                switch (account.UpdateEmail((int)HttpContext.Session.GetInt32("id")!, ce.newEmail))
                {
                    case 0:
                        successBox = true;
                        info = "Your email has been successfully changed.";
                        HttpContext.Session.Remove("email");
                        HttpContext.Session.SetString("email", ce.newEmail);
                        break;
                    case 1:
                        warningBox = true;
                        info = "This email is already taken.";
                        break;
                    case -1:
                        dangerBox = true;
                        info = "The server was unable to process the request. Sorry for the inconvenience.";
                        break;
                }
            }
        }
        else dangerBox = true;
        OnGet();
    }

    public void OnPostChangePassword()
    {
        successBox = warningBox = dangerBox = false;
        if (ModelState.ErrorCount - 4 == 0)
        {
            if (!account.CheckPasswordCompatibility((int)HttpContext.Session.GetInt32("id")!, cp.oldPassword))
            {
                dangerBox = true;
                info = "Wrong old password provided.";
            }
            else
            {
                switch (account.UpdatePassword((int)HttpContext.Session.GetInt32("id")!, cp.newPassword))
                {
                    case true:
                        successBox = true;
                        info = "Your password has been successfully changed.";
                        break;
                    case false:
                        dangerBox = true;
                        info = "The server was unable to process the request. Sorry for the inconvenience.";
                        break;
                }
            }
        }
        else dangerBox = true;
        OnGet();
    }

    public void OnPostRemoveAccount()
    {
        successBox = warningBox = dangerBox = false;
        if (ModelState.ErrorCount - 6 == 0)
        {
            if (!account.CheckPasswordCompatibility((int)HttpContext.Session.GetInt32("id")!, ra.password))
            {
                dangerBox = true;
                info = "Wrong password provided.";
            }
            else
            {
                switch (account.RemoveUser((int)HttpContext.Session.GetInt32("id")!))
                {
                    case true:
                        Response.Redirect("/Logout");
                        break;
                    case false:
                        dangerBox = true;
                        info = "The server was unable to process the request. Sorry for the inconvenience.";
                        break;
                }
            }
        }
        else dangerBox = true;
        OnGet();
    }
}

FenXs/FenXs/Pages/Settings/Index.cshtml
@page
@model SettingsIndexModel
@{
    Layout = "LayoutLogged";
    ViewData["Description"] = "- Settings";
    ViewData["Login"] = @Model.user.login;
    ViewData["FenXs-Stars"] = @Model.user.fenxsStars;
}

@if (@Model.user.admin)
{
    <div class="row m-2">
        <a href="/AdminPanel/" class="btn btn-primary border border-dark">Admin Panel</a>
    </div>
}
@if (Model.dangerBox)
{
    <div class="alert alert-dismissible mx-2 bg-danger border border-2 border-dark shadow-lg" role="alert">
        <span asp-validation-for="ce!.oldEmail" class="d-block"></span>
        <span asp-validation-for="ce!.newEmail" class="d-block"></span>
        <span asp-validation-for="ce!.repeatNewEmail" class="d-block"></span>
        <span asp-validation-for="cp!.oldPassword" class="d-block"></span>
        <span asp-validation-for="cp!.oldPassword" class="d-block"></span>
        <span asp-validation-for="cp!.repeatNewPassword" class="d-block"></span>
        <span asp-validation-for="ra!.password" class="d-block"></span>
        <span class="d-block">@Model.info</span>
        <button type="button" class="btn-close position-absolute top-50 translate-middle-y" data-bs-dismiss="alert"
                aria-label="Close"></button>
    </div>
}
@if (Model.warningBox)
{
    <div class="alert alert-dismissible mx-2 bg-warning border border-2 border-dark shadow-lg" role="alert">
        <span class="d-block">@Model.info</span>
        <button type="button" class="btn-close position-absolute top-50 translate-middle-y" data-bs-dismiss="alert"
                aria-label="Close"></button>
    </div>
}
@if (Model.successBox)
{
    <div class="alert alert-dismissible mx-2 bg-success border border-2 border-dark shadow-lg" role="alert">
        <span class="d-block">@Model.info</span>
        <button type="button" class="btn-close position-absolute top-50 translate-middle-y" data-bs-dismiss="alert"
                aria-label="Close"></button>
    </div>
}
<div class="row justify-content-center FenXs-Font-Forms text-dark m-2 mt-3">
    <div class="col-12 col-md FenXs-Wooden me-2 border border-2 border-dark rounded shadow-sm">
        <div class="text-center h4 mt-1">
            Change E-mail
        </div>
        <div>
            Your E-mail: <span class="FenXs-Text-Dark-Shadow text-warning">@Model.user.email</span>
        </div>
        <form method="post" asp-page-handler="ChangeEmail">
            <div class="form-group my-2">
                <input type="email" asp-for="ce!.oldEmail" class="form-control form-control-sm border border-dark"
                       placeholder="Your Old E-mail">
            </div>
            <div class="form-group my-2">
                <input type="email" asp-for="ce!.newEmail" class="form-control form-control-sm border border-dark"
                       placeholder="Your New E-mail">
            </div>
            <div class="form-group my-2">
                <input type="email" asp-for="ce!.repeatNewEmail" class="form-control form-control-sm border border-dark"
                       placeholder="Repeat New E-mail">
            </div>
            <div class="form-group my-2">
                <button type="submit" class="btn btn-success w-100 border border-dark">Change E-mail</button>
            </div>
        </form>
    </div>
    <div class="col-12 col-md FenXs-Wooden ms-2 border border-2 border-dark rounded shadow-sm">
        <div class="text-center h4 mt-1">
            Change Password
        </div>
        <div>
            &nbsp
        </div>
        <form method="post" asp-page-handler="ChangePassword">
            <div class="form-group my-2">
                <input type="password" asp-for="cp!.oldPassword" class="form-control form-control-sm border border-dark"
                       placeholder="Your Old Password">
            </div>
            <div class="form-group my-2">
                <input type="password" asp-for="cp!.newPassword" class="form-control form-control-sm border border-dark"
                       placeholder="Your New Password">
            </div>
            <div class="form-group my-2">
                <input type="password" asp-for="cp!.repeatNewPassword"
                       class="form-control form-control-sm border border-dark" placeholder="Repeat New Password">
            </div>
            <div class="form-group my-2">
                <button type="submit" class="btn btn-success w-100 border border-dark">Change Password</button>
            </div>
        </form>
    </div>
</div>
<div class="row justify-content-center FenXs-Font-Forms text-dark m-2 mt-3">
    <div class="col-12 col-md bg-danger border border-2 border-dark rounded shadow-sm">
        <div class="text-center h4 mt-1">
            Remove Account
        </div>
        <form method="post" asp-page-handler="RemoveAccount">
            <div class="form-group my-2">
                <input type="password" asp-for="ra!.password" class="form-control form-control-sm border border-dark"
                       placeholder="Your Password">
            </div>
            <div class="form-group my-2">
                <button type="submit" class="btn btn-warning w-100 border border-dark">Remove Account</button>
            </div>
        </form>
    </div>
</div>