FenXs/FenXs/Pages/AdminPanel/Index.cshtml.cs
using PageModels.AdminPageModel;

namespace FenXs.Pages;

public class AdminPanelIndexModel : AdminPageModel { }

FenXs/FenXs/Pages/AdminPanel/News.cshtml.cs
using PageModels.AdminPageModel;
using NewsM = FenXsData.Models.NewsModel.News;
using NewsCM = FenXsData.Models.NewsModel.NewsCategory;
using FenXs.DataAccessLayer.News;
using ILogger = FenXsData.Infrastructure.Logger.ILogger;

namespace FenXs.Pages;

public class NewsModel : AdminPageModel
{
    private News news;
    public List<NewsM> listOfNews;
    public List<NewsCM> listOfNewsCategories;

    public NewsModel(IConfiguration configuration, ILogger _logger)
    {
        news = new News(configuration, _logger);
        listOfNews = news.GetNews(false);
        listOfNewsCategories = news.GetCategories();
    }
}

FenXs/FenXs/Pages/AdminPanel/News/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using PageModels.AdminPageModel;
using FenXs.DataAccessLayer.News;
using NewsM = FenXsData.Models.NewsModel.News;
using NewsCM = FenXsData.Models.NewsModel.NewsCategory;
using ILogger = FenXsData.Infrastructure.Logger.ILogger;

namespace FenXs.Pages;

public class NewsAddModel : AdminPageModel
{
    private News news;
    [BindProperty]
    public NewsM? newsM { get; set; }
    public List<NewsCM> listOfNewsCategories;
    public string? info;
    public bool dangerBox;

    public NewsAddModel(IConfiguration configuration, ILogger _logger)
    {
        news = new News(configuration, _logger);
        listOfNewsCategories = news.GetCategories();
    }

    public void OnPost()
    {
        if (ModelState.IsValid)
        {
            if (news.InsertNews(newsM!)) Response.Redirect("../News");
            else info = "Currently, the server cannot fulfill the request.";
        }
        dangerBox = true;
        OnGet();
    }
}

FenXs/FenXs/Pages/AdminPanel/News/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using PageModels.AdminPageModel;
using FenXs.DataAccessLayer.News;
using ILogger = FenXsData.Infrastructure.Logger;

namespace FenXs.Pages;

public class NewsDeleteModel : AdminPageModel
{
    [BindProperty(SupportsGet = true)]
    public int id { get; set; }
    private News news;

    public NewsDeleteModel(IConfiguration configuration, ILogger.ILogger _logger)
    {
        news = new News(configuration, _logger);
    }

    override public void OnGet()
    {
        if (!IsUserLogged()) Response.Redirect("/");
        if (!user.admin) Response.Redirect("/Main");
        if (!news.RemoveNews(id)) Response.Redirect("/Error");
        Response.Redirect("../News");
    }
}

FenXs/FenXs/Pages/AdminPanel/News/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using PageModels.AdminPageModel;
using FenXs.DataAccessLayer.News;
using NewsM = FenXsData.Models.NewsModel.News;
using NewsCM = FenXsData.Models.NewsModel.NewsCategory;
using ILogger = FenXsData.Infrastructure.Logger.ILogger;

namespace FenXs.Pages;

public class NewsEditModel : AdminPageModel
{
    [BindProperty(SupportsGet = true)]
    public int id { get; set; }
    private News news;
    [BindProperty]
    public NewsM? newsM { get; set; }
    public List<NewsCM> listOfNewsCategories;
    public bool dangerBox;
    public string? info;

    public NewsEditModel(IConfiguration configuration, ILogger _logger)
    {
        news = new News(configuration, _logger);
        listOfNewsCategories = news.GetCategories();
    }

    public void OnPost()
    {
        if (ModelState.IsValid)
        {
            newsM!.id = id;
            if (news.UpdateNews(newsM!)) Response.Redirect("../News");
            else info = "Currently, the server cannot fulfill the request.";
        }
        dangerBox = true;
        OnGet();
    }
}

FenXs/FenXs/Pages/AdminPanel/TurnOffServer.cshtml.cs
using System.Diagnostics;
using PageModels.AdminPageModel;
using ILogger = FenXsData.Infrastructure.Logger.ILogger;

namespace FenXs.Pages;

public class TurnOffServerModel : AdminPageModel
{
    private ILogger _logger;

    public TurnOffServerModel(ILogger _logger)
    {
        this._logger = _logger;
    }

    override public void OnGet()
    {
        if (!IsUserLogged()) Response.Redirect("/");
        if (!user.admin) Response.Redirect("/Main");
    }

    public void OnPostTurnOffServerStart()
    {
        try
        {
            Process.Start("D:\\Scripts\\TurnOffServerStart.exe");
        }
        catch (Exception ex)
        {
            _logger.SaveLog(ex.Message);
        }
    }

    public void OnPostTurnOffServerStop()
    {
        try
        {
            Process.Start("D:\\Scripts\\TurnOffServerStop.exe");
        }
        catch (Exception ex)
        {
            _logger.SaveLog(ex.Message);
        }
    }
}

FenXs/FenXs/Pages/AdminPanel/Users.cshtml.cs
using PageModels.AdminPageModel;
using FenXs.DataAccessLayer.Account;
using UserFull = FenXsData.Models.UserModel.UserFull;
using ILogger = FenXsData.Infrastructure.Logger.ILogger;

namespace FenXs.Pages;

public class UsersModel : AdminPageModel
{
    private Account account;
    public List<UserFull> listOfUsers;

    public UsersModel(IConfiguration configuration, ILogger _logger)
    {
        account = new Account(configuration, _logger);
        listOfUsers = account.GetAllUsers();
    }
}

FenXs/FenXs/Pages/AdminPanel/Users/SetActive.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using PageModels.AdminPageModel;
using FenXs.DataAccessLayer.Account;
using ILogger = FenXsData.Infrastructure.Logger.ILogger;

namespace FenXs.Pages;

public class UsersSetActiveModel : AdminPageModel
{
    [BindProperty(SupportsGet = true)]
    public int id { get; set; }
    [BindProperty(SupportsGet = true)]
    public bool set { get; set; }
    private Account account;

    public UsersSetActiveModel(IConfiguration configuration, ILogger _logger)
    {
        account = new Account(configuration, _logger);
    }

    override public void OnGet()
    {
        if (!IsUserLogged()) Response.Redirect("/");
        if (!user.admin) Response.Redirect("/Main");
        if (!account.UpdateActive(id, !set)) Response.Redirect("/Error");
        Response.Redirect("../Users");
    }
}

FenXs/FenXs/Pages/AdminPanel/Users/SetAdmin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using PageModels.AdminPageModel;
using FenXs.DataAccessLayer.Account;
using ILogger = FenXsData.Infrastructure.Logger.ILogger;

namespace FenXs.Pages;

public class UsersSetAdminModel : AdminPageModel
{
    [BindProperty(SupportsGet = true)]
    public int id { get; set; }
    [BindProperty(SupportsGet = true)]
    public bool set { get; set; }
    private Account account;

    public UsersSetAdminModel(IConfiguration configuration, ILogger _logger)
    {
        account = new Account(configuration, _logger);
    }

    override public void OnGet()
    {
        if (!IsUserLogged()) Response.Redirect("/");
        if (!user.admin) Response.Redirect("/Main");
        if (!account.UpdateAdmin(id, !set)) Response.Redirect("/Error");
        Response.Redirect("../Users");
    }
}

FenXs/FenXs/Pages/AdminPanel/Users/SetBanned.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using PageModels.AdminPageModel;
using FenXs.DataAccessLayer.Account;
using ILogger = FenXsData.Infrastructure.Logger.ILogger;

namespace FenXs.Pages;

public class UsersSetBannedModel : AdminPageModel
{
    [BindProperty(SupportsGet = true)]
    public int id { get; set; }
    [BindProperty(SupportsGet = true)]
    public bool set { get; set; }
    private Account account;

    public UsersSetBannedModel(IConfiguration configuration, ILogger _logger)
    {
        account = new Account(configuration, _logger);
    }

    override public void OnGet()
    {
        if (!IsUserLogged()) Response.Redirect("/");
        if (!user.admin) Response.Redirect("/Main");
        if (!account.UpdateBanned(id, !set)) Response.Redirect("/Error");
        Response.Redirect("../Users");
    }
}

FenXs/FenXs/Pages/AdminPanel/Users/SetModerator.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using PageModels.AdminPageModel;
using FenXs.DataAccessLayer.Account;
using ILogger = FenXsData.Infrastructure.Logger.ILogger;

namespace FenXs.Pages;

public class UsersSetModeratorModel : AdminPageModel
{
    [BindProperty(SupportsGet = true)]
    public int id { get; set; }
    [BindProperty(SupportsGet = true)]
    public bool set { get; set; }
    private Account account;

    public UsersSetModeratorModel(IConfiguration configuration, ILogger _logger)
    {
        account = new Account(configuration, _logger);
    }

    override public void OnGet()
    {
        if (!IsUserLogged()) Response.Redirect("/");
        if (!user.admin) Response.Redirect("/Main");
        if (!account.UpdateModerator(id, !set)) Response.Redirect("/Error");
        Response.Redirect("../Users");
    }
}

FenXs/FenXs/Pages/AdminPanel/Index.cshtml
@page
@model AdminPanelIndexModel
@{
    Layout = "LayoutLogged";
    ViewData["Description"] = "- Admin Panel";
    ViewData["Login"] = @Model.user.login;
    ViewData["FenXs-Stars"] = @Model.user.fenxsStars;
    ViewBag.IsAdminPanel = true;
}

<div class="row m-2">
    <a href="/Settings" class="btn btn-primary border border-dark rounded shadow">Back To Settings</a>
</div>
<div class="row h1 m-2">
    <a href="/AdminPanel/Users" class="col-12 col-md Settings link-light bg-dark my-2 mx-md-2 rounded shadow">Users</a>
    <a href="/AdminPanel/News" class="col-12 col-md Settings link-light bg-dark my-2 mx-md-2 rounded shadow">News</a>
</div>
<div class="row h1 m-2">
    <a href="/AdminPanel/TurnOffServer" class="col-12 col-md TurnOffServer link-light bg-danger my-2 mx-md-2 rounded shadow">Turn Off Server</a>
</div>

FenXs/FenXs/Pages/AdminPanel/News.cshtml
@page
@model NewsModel
@{
    Layout = "LayoutLogged";
    ViewData["Description"] = "- Admin Panel - News";
    ViewData["Login"] = @Model.user.login;
    ViewData["FenXs-Stars"] = @Model.user.fenxsStars;
}

<div class="row m-2">
    <div class="col-12 col-md p-0 my-1 my-md-0 me-md-1">
        <a href="News/Add" class="btn btn-success w-100 border border-dark rounded shadow">Add News</a>
    </div>
    <div class="col-12 col-md p-0 my-1 my-md-0 ms-md-1">
        <a href="Index" class="btn btn-primary w-100 border border-dark rounded shadow">Back To Admin Panel</a>
    </div>
</div>
<div class="m-2 mt-3">
    <table class="table table-striped table-dark border border-light shadow">
        <thead>
            <tr class="text-center">
                <th scope="col" class="border-end border-light">ID</th>
                <th scope="col" class="border-end border-light">Title</th>
                <th scope="col" class="border-end border-light">Text</th>
                <th scope="col" class="border-end border-light">Date</th>
                <th scope="col" class="border-end border-light">Category</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var news in Model.listOfNews)
            {
                <tr class="FenXs-Font-Smaller">
                    <th scope="row" class="text-center border-end border-light">@news.id</th>
                    <td class="border-end border-light">@news.title</td>
                    <td class="border-end border-light">@news.text</td>
                    <td class="text-center border-end border-light">@news.date</td>
                    <td class="text-center border-end border-light">
                        @foreach (var newsCategory in Model.listOfNewsCategories)
                        {
                            if (news.idOfCategory == newsCategory.id)
                            {
                                <span>@newsCategory.name</span>
                                break;
                            }
                        }
                    </td>
                    <td class="text-center">
                        <a asp-page="News/Edit" asp-route-id="@news.id"
                           class="link-success fw-bold FenXs-Text-NoShadow">Edit</a> |
                        <a asp-page="News/Delete" asp-route-id="@news.id"
                           class="link-danger fw-bold FenXs-Text-NoShadow">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

FenXs/FenXs/Pages/AdminPanel/TurnOffServer.cshtml
@page
@model TurnOffServerModel
@{
    Layout = "LayoutLogged";
    ViewData["Description"] = "- Admin Panel - Turn Off Server";
    ViewData["Login"] = @Model.user.login;
    ViewData["FenXs-Stars"] = @Model.user.fenxsStars;
    ViewBag.IsTurnOffPage = true;
}

<div class="m-2">
    <a href="Index" class="btn btn-primary w-100 border border-dark rounded shadow">Back To Admin Panel</a>
</div>
<div class="row m-2 text-center">
    <form method="post">
        <button id="TurnOffServerStart" asp-page-handler="TurnOffServerStart"
                class="col-12 col-md my-2 mx-md-2 pt-2 btn btn-danger border border-2 border-dark rounded shadow">
            Turn Off
        </button>
        <button id="TurnOffServerStop" asp-page-handler="TurnOffServerStop"
                class="col-12 col-md my-2 mx-md-2 pt-2 btn btn-success border border-2 border-dark rounded shadow">
            Cancel
        </button>
    </form>
</div>
<div id="TurnOffServerText" class="m-2 h1 text-center">
    Turn Off Server?
</div>

FenXs/FenXs/Pages/AdminPanel/Users.cshtml
@page
@model UsersModel
@{
    Layout = "LayoutLogged";
    ViewData["Description"] = "- Admin Panel - Users";
    ViewData["Login"] = @Model.user.login;
    ViewData["FenXs-Stars"] = @Model.user.fenxsStars;
}

<div class="m-2">
    <a href="Index" class="btn btn-primary w-100 border border-dark rounded shadow">Back To Admin Panel</a>
</div>
<div class="m-2 mt-3">
    <table class="table table-striped table-dark border border-light shadow">
        <thead>
            <tr class="text-center">
                <th scope="col" class="border-end border-light">Id</th>
                <th scope="col" class="border-end border-light">Email</th>
                <th scope="col" class="border-end border-light">Active</th>
                <th scope="col" class="border-end border-light">Banned</th>
                <th scope="col" class="border-end border-light">Admin</th>
                <th scope="col" class="border-end border-light">Moderator</th>
                <th scope="col" class="border-end border-light">Stars</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model.listOfUsers)
            {
                <tr class="FenXs-Font-Smaller">
                    <th scope="row" class="text-center border-end border-light">@user.id</th>
                    <td scope="row" class="border-end border-light">@user.email</td>
                    <td scope="row" class="text-success text-center border-end border-light">@user.active</td>
                    <td scope="row" class="text-danger text-center border-end border-light">@user.banned</td>
                    <td scope="row" class="text-warning text-center border-end border-light">@user.admin</td>
                    <td scope="row" class="text-primary text-center border-end border-light">@user.moderator</td>
                    <td scope="row" class="text-center border-end border-light">@user.fenxsStars</td>
                    <td scope="row" class="text-center">
                        <a asp-page="Users/SetActive" asp-route-id="@user.id" asp-route-set="@user.active"
                           class="link-success fw-bold FenXs-Text-NoShadow">Active</a> |
                        <a asp-page="Users/SetBanned" asp-route-id="@user.id" asp-route-set="@user.banned"
                           class="link-danger fw-bold FenXs-Text-NoShadow">Ban</a> |
                        <a asp-page="Users/SetAdmin" asp-route-id="@user.id" asp-route-set="@user.admin"
                           class="link-warning fw-bold FenXs-Text-NoShadow">Admin</a> |
                        <a asp-page="Users/SetModerator" asp-route-id="@user.id" asp-route-set="@user.moderator"
                           class="link-primary fw-bold FenXs-Text-NoShadow">Moderator</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>