FenXs/FenXs/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FenXs.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? requestId { get; set; }
    public bool showRequestId => !string.IsNullOrEmpty(requestId);
    private readonly ILogger<ErrorModel> logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        this.logger = logger;
    }

    public void OnGet()
    {
        requestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

FenXs/FenXs/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using PageModels.VisitorPageModel;
using FenXsData.Models.RegistrationModel;
using FenXsData.Models.LoginModel;
using FenXsData.Models.UserModel;
using FenXs.DataAccessLayer.Account;
using ILogger = FenXsData.Infrastructure.Logger.ILogger;

namespace FenXs.Pages;

public class IndexModel : VisitorPageModel
{
    [BindProperty]
    public Registration? r { get; set; }
    [BindProperty]
    public Login? l { get; set; }
    private Account account;
    public bool dangerBox, warningBox, successBox;
    public string? info;

    public IndexModel(IConfiguration configuration, ILogger _logger)
    {
        account = new Account(configuration, _logger);
    }

    public IActionResult OnPostLogin()
    {
        dangerBox = warningBox = successBox = false;
        if (ModelState.ErrorCount - 4 == 0)
        {
            UserReturn userReturn = account.GetUser(l!);
            if (userReturn.user != null)
            {
                HttpContext.Session.SetInt32("id", userReturn.user.id);
                HttpContext.Session.SetString("login", userReturn.user.login);
                HttpContext.Session.SetString("email", userReturn.user.email);
                HttpContext.Session.SetInt32("admin", Convert.ToInt32(userReturn.user.admin));
                HttpContext.Session.SetInt32("fenXs_Stars", userReturn.user.fenxsStars);
                Response.Cookies.Append("whereLogged", "1");
                return RedirectToPage("/Main");
            }
            switch (userReturn.statusCode)
            {
                case 1:
                    warningBox = true;
                    info = "Account with this login does not exist.";
                    break;
                case 2:
                    warningBox = true;
                    info = "Incorrect password.";
                    break;
                case 3:
                    warningBox = true;
                    info = "This account is not activated.";
                    break;
                case 4:
                    warningBox = true;
                    info = "This account is banned.";
                    break;
                case -1:
                    dangerBox = true;
                    info = "Page server is offline. Sorry for the inconvenience.";
                    break;
                default: return RedirectToPage("/Error");
            }
        }
        else dangerBox = true;
        return Page();
    }

    public IActionResult OnPostRegistration()
    {
        dangerBox = warningBox = successBox = false;
        if (ModelState.ErrorCount - 2 == 0)
        {
            switch (account.InsertUser(r!))
            {
                case 0:
                    successBox = true;
                    info = "A link to activate the account has been sent to the given e-mail address.";
                    Response.Cookies.Append("whereLogged", "1");
                    break;
                case 1:
                    warningBox = true;
                    info = "This Login is already taken.";
                    break;
                case 2:
                    warningBox = true;
                    info = "This Email is already taken.";
                    break;
                case -1:
                    dangerBox = true;
                    info = "Page server is offline. Sorry for the inconvenience.";
                    break;
                default: return RedirectToPage("/Error");
            }
        }
        else dangerBox = true;
        return Page();
    }
}

FenXs/FenXs/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FenXs.Pages;

public class LogoutModel : PageModel
{
    public IActionResult OnGet()
    {
        HttpContext.Session.Clear();
        return RedirectToPage("/Index");
    }
}

FenXs/FenXs/Pages/Main.cshtml.cs
using PageModels.UserPageModel;
using NewsM = FenXsData.Models.NewsModel.News;
using FenXs.DataAccessLayer.News;
using ILogger = FenXsData.Infrastructure.Logger.ILogger;

namespace FenXs.Pages;

public class MainModel : UserPageModel
{
    private News news;
    public List<NewsM> listOfNews;

    public MainModel(IConfiguration configuration, ILogger _logger)
    {
        news = new News(configuration, _logger);
        listOfNews = news.GetNews(true);
    }
}

FenXs/FenXs/Pages/NotFound.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FenXs.Pages;

public class NotFoundModel : PageModel { }

FenXs/FenXs/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FenXs.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet() { }
}

FenXs/FenXs/Pages/Index.cshtml
@page
@model IndexModel
@{
    Layout = "LayoutDefault";
    ViewBag.IsIndex = true;
}

<div class="container IndexError">
    @if (Model.dangerBox)
    {
        <div class="alert alert-dismissible bg-danger border border-2 border-dark shadow-lg" role="alert">
            <span asp-validation-for="r!.login" class="d-block"></span>
            <span asp-validation-for="r!.email" class="d-block"></span>
            <span asp-validation-for="r!.password" class="d-block"></span>
            <span asp-validation-for="r!.confirmPassword" class="d-block"></span>
            <span asp-validation-for="l!.login" class="d-block"></span>
            <span asp-validation-for="l!.password" class="d-block"></span>
            <span class="d-block">@Model.info</span>
            <button type="button" class="btn-close position-absolute top-50 translate-middle-y" data-bs-dismiss="alert"
                    aria-label="Close"></button>
        </div>
    }
    @if (Model.warningBox)
    {
        <div class="alert alert-dismissible bg-warning border border-2 border-dark shadow-lg" role="alert">
            <span class="d-block">@Model.info</span>
            <button type="button" class="btn-close position-absolute top-50 translate-middle-y" data-bs-dismiss="alert"
                    aria-label="Close"></button>
        </div>
    }
    @if (Model.successBox)
    {
        <div class="alert alert-dismissible bg-success border border-2 border-dark shadow-lg" role="alert">
            <span class="d-block">@Model.info</span>
            <button type="button" class="btn-close position-absolute top-50 translate-middle-y" data-bs-dismiss="alert"
                    aria-label="Close"></button>
        </div>
    }
</div>
<div id="SignInLoginInBox" class="container IndexMenu FenXs-Font-Forms shadow-lg">
    <div class="row text-center IndexMenuTab">
        <div id="LoginInSelector" class="col FenXs-Dark-Wooden rounded-top border border-end-0 border-2 border-dark">
            Login In
        </div>
        <div id="SignInSelector" class="col FenXs-Wooden rounded-top border border-2 border-dark">
            Sign In
        </div>
    </div>
    <div class="row FenXs-Wooden border border-top-0 border-2 border-dark rounded-bottom">
        <div id="LoginInBox" style="display:none">
            <div class="row IndexMenuForm">
                <div class="col-4 border-end border-2 border-dark">
                    <label asp-for="l!.login" class="mt-4 p-1 w-100">Login</label>
                    <label asp-for="l!.password" class="my-2 p-1 w-100">Password</label>
                </div>
                <div class="col-8">
                    <form method="post" onsubmit="return ValidateLoginIn()" asp-page-handler="Login">
                        <div class="form-group mt-4">
                            <input type="text" asp-for="l!.login" class="form-control p-1 border border-dark"
                                   placeholder="Your Login">
                        </div>
                        <div class="form-group my-2">
                            <input type="password" asp-for="l!.password" class="form-control p-1 border border-dark"
                                   placeholder="Your Password">
                        </div>
                        <div class="form-group my-2 mb-0">
                            <button type="submit" class="btn btn-success p-1 w-100 border border-dark">Login In</button>
                        </div>
                        <div class="form-group text-center small">
                            <a href="*" class="link-light">Forget Your Password?</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div id="SignInBox">
            <div class="row IndexMenuForm">
                <div class="col-4 border-end border-2 border-dark">
                    <label asp-for="r!.login" class="mt-3 p-1 w-100">Login</label>
                    <label asp-for="r!.email" class="mt-2 p-1 w-100">E-Mail</label>
                    <label asp-for="r!.password" class="mt-2 p-1 w-100">Password</label>
                    <label asp-for="r!.confirmPassword" class="mt-2 p-1 w-100">Confirm P.</label>
                    <button id="SignInInfoBtn" class="btn FenXs-Dark-Wooden-Btn btn-sm mt-2 p-1 w-100">Info</button>
                </div>
                <div class="col-8">
                    <form method="post" onsubmit="return ValidateSignIn()" asp-page-handler="Registration">
                        <div class="form-group mt-3">
                            <input type="text" asp-for="r!.login" class="form-control form-control-sm border border-dark"
                                   placeholder="e.g. Player007">
                        </div>
                        <div class="form-group mt-2">
                            <input type="email" asp-for="r!.email"
                                   class="form-control form-control-sm border border-dark"
                                   placeholder="e.g. player007@gmail.com">
                        </div>
                        <div class="form-group mt-2">
                            <input type="password" asp-for="r!.password"
                                   class="form-control form-control-sm border border-dark" placeholder="Your Password">
                        </div>
                        <div class="form-group mt-2">
                            <input type="password" asp-for="r!.confirmPassword"
                                   class="form-control form-control-sm border border-dark"
                                   placeholder="Confirm Your Password">
                        </div>
                        <div class="form-group mt-2">
                            <button type="submit" class="btn btn-success btn-sm w-100 border border-dark">
                                Sign
                                In
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="SignInInfoBox" class="container IndexMenu FenXs-Wooden p-1 px-2 border border-2 border-dark rounded shadow-lg"
     style="display:none;">
    <ol class="FenXs-Text-Smaller text-justify p-1 ps-3">
        <li class="pt-3">
            Login must start with a letter and end with a letter or a number. There may be a dash
            or the floor in the middle. Login must be between 3 and 15 characters long.
        </li>
        <li class="pt-3">
            Password must contain only letters and numbers and must be between 8 and 30 characters
            long.
        </li>
        <li class="pt-3">E-mail must conform to an international standard.</li>
    </ol>
    <button id="SignInInfoBtnQuit" class="float-bottom btn btn-danger btn-sm w-100 border border-dark">Quit</button>
</div>

FenXs/FenXs/Pages/Logout.cshtml
@page
@model LogoutModel
@{
    Layout = null;
}

FenXs/FenXs/Pages/Main.cshtml
@page
@model MainModel
@{
    Layout = "LayoutLogged";
    ViewData["Description"] = "- Main";
    ViewData["Login"] = @Model.user.login;
    ViewData["FenXs-Stars"] = @Model.user.fenxsStars;
    ViewBag.IsMain = true;
}

<div class="row h1 m-2">
    <a href="*" class="col-12 col-md ServerBtn FenXsGame my-2 mx-md-2 rounded shadow">
        FenXs Game
    </a>
    <a href="https://FenXs.ddns.net:8888" class="col-12 col-md ServerBtn Minecraft my-2 mx-md-2 rounded shadow">
        Minecraft
    </a>
</div>
<div class="row m-2 mt-3">
    @if (Model.listOfNews == null)
    {
        <div class="alert alert-dismissible bg-danger border border-2 border-dark shadow" role="alert">
            Failed to download the news list. Sorry for the inconvenience.
            <button type="button" class="btn-close position-absolute top-50 translate-middle-y" data-bs-dismiss="alert"
                    aria-label="Close"></button>
        </div>
    }
    else
    {
        <div class="text-light bg-light bg-opacity-25 border rounded shadow">
            <div class="h2 text-center mt-2">News</div>
            @foreach (var n in Model.listOfNews)
            {
                <div class="my-2 bg-dark bg-opacity-75 border border-dark rounded shadow-sm">
                    <div class="h3 mb-0 mt-1 text-success text-center border-bottom border-dark">@n.title</div>
                    <div class="px-2 mb-0 mt-1 text-justify border-bottom border-dark">@n.text</div>
                    <div class="px-2 mt-1 text-end FenXs-Text-Smaller">
                        <span class="text-danger">Team FenXs</span> -
                        @n.date.ToString()
                    </div>
                </div>
            }
        </div>
    }
</div>

FenXs/FenXs/Pages/NotFound.cshtml
@page
@model NotFoundModel
@{
    Layout = "LayoutDefault";
    ViewData["Description"] = "- Page Not Found";
}

<div class="text-center FenXs-Text-Shadow">
    <span class="display-1">Error 404</span><br />
    <a href="/Index" class="link-light">Back To Main Page</a>
</div>